### ISSUE TITLE
Example project no longer works with latest JAR

### ISSUE THREAD

**Issue by yatesco** [mathias/boot-sassc-example#1]
It seems namespaces have changed and config options have changed.

**Comment by mathias** [comment]
I will take a look at updating this tonight and close when a new version is pushed.

Thanks for reporting.

**Comment by mathias** [comment]
Are you using this with boot2?

**Comment by mathias** [comment]
Also, an update on this: I've got it updated, but the boot task doesn't seem to be working anymore, so I'm trying to debug the task itself.

**Comment by yatesco** [comment]
Yep, boot2. The task itself worked when I used the config from the github
page of the task itself rather than the example.

**Comment by mathias** [comment]
Project has been updated; let me know if it is still an issue.
